
export const plans = [
  {
    id: "1-month",
    name: "1 Month",
    duration: "1 month",
    price: 16.00,
    price_monthly: 16.00,
    savings: null,
    features: [
      "4K Ultra HD Streaming Quality",
      "25,000+ Live Channels Worldwide",
      "120,000+ Movies & TV Shows",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Canadian Support",
      "Multi-Device Compatibility",
    ],
    isPopular: false,
    url: "/checkout?plan=1-month"
  },
  {
    id: "3-months",
    name: "3 Months",
    duration: "3 months",
    price: 39.00,
    price_monthly: 13.00,
    savings: "Save 19%",
    features: [
      "4K Ultra HD Streaming Quality",
      "25,000+ Live Channels Worldwide",
      "120,000+ Movies & TV Shows",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Canadian Support",
      "Multi-Device Compatibility",
    ],
    isPopular: false,
    url: "/checkout?plan=3-months"
  },
  {
    id: "6-months",
    name: "6 Months",
    duration: "6 months",
    price: 60.00,
    price_monthly: 10.00,
    savings: "Save 38%",
    features: [
      "4K Ultra HD Streaming Quality",
      "25,000+ Live Channels Worldwide",
      "120,000+ Movies & TV Shows",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Canadian Support",
      "Multi-Device Compatibility",
    ],
    isPopular: false,
    url: "/checkout?plan=6-months"
  },
  {
    id: "12-months",
    name: "12 Months",
    duration: "12 months",
    price: 90.00,
    price_monthly: 7.50,
    savings: "Save 53%",
    features: [
      "4K Ultra HD Streaming Quality",
      "25,000+ Live Channels Worldwide",
      "120,000+ Movies & TV Shows",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Canadian Support",
      "Multi-Device Compatibility",
    ],
    isPopular: true,
    url: "/checkout?plan=12-months"
  },
];
