
export const plans = [
  {
    id: "1-month",
    name: "1 Month",
    duration: "1 month",
    price: 16.00,
    price_monthly: 16.00,
    savings: null,
    features: [
      "4K Ultra HD Streaming Quality",
      "24,000+ Live Channels Worldwide",
      "80,000+ Movies & Series",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Customer Support",
      "Multi-Device Compatibility",
    ],
    isPopular: false,
    checkoutUrl: "https://flujipay.com/payment/e1JWrpo7MBOGuaq0axpgtaxxIBTcFRoj",
  },
  {
    id: "3-months",
    name: "3 Months",
    duration: "3 months",
    price: 39.00,
    price_monthly: 13.00,
    savings: "Save 19%",
    features: [
      "4K Ultra HD Streaming Quality",
      "24,000+ Live Channels Worldwide",
      "80,000+ Movies & Series",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Customer Support",
      "Multi-Device Compatibility",
    ],
    isPopular: false,
    checkoutUrl: "https://flujipay.com/payment/npi8bNFKa60nGloEpZuBguh6tBFSueUN",
  },
  {
    id: "6-months",
    name: "6 Months",
    duration: "6 months",
    price: 60.00,
    price_monthly: 10.00,
    savings: "Save 38%",
    features: [
      "4K Ultra HD Streaming Quality",
      "24,000+ Live Channels Worldwide",
      "80,000+ Movies & Series",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Customer Support",
      "Multi-Device Compatibility",
    ],
    isPopular: false,
    checkoutUrl: "https://flujipay.com/payment/DkNU7UJ2dliHkpGRF7HHhW3JJajmwi3m",
  },
  {
    id: "12-months",
    name: "12 Months",
    duration: "12 months",
    price: 90.00,
    price_monthly: 7.50,
    savings: "Save 53%",
    features: [
      "4K Ultra HD Streaming Quality",
      "24,000+ Live Channels Worldwide",
      "80,000+ Movies & Series",
      "Premium PPV Events Included",
      "Instant VOD Access",
      "Smart EPG & Catch-Up TV",
      "24/7 Customer Support",
      "Multi-Device Compatibility",
    ],
    isPopular: true,
    checkoutUrl: "https://flujipay.com/payment/y59giDeQUiwnLBXIMYDo4ZRbLBpjeNmG",
  },
];
